apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server_tokens off;
    client_max_body_size 32m;

    upstream Backend {
      server gohello;
    }

    server {
      # expose /nginx_status but on a different port to avoid
      # external visibility / conflicts with the app.
      listen 8090;
      listen 80;

      location /nginx_status {
        stub_status on;
        access_log off;
      }
      location / {
          proxy_pass http://Backend;
      }
    }
