---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: gohello
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: gohello
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: nginx
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf # mount nginx-conf volumn to /etc/nginx
              subPath: default.conf
              readOnly: true
              name: nginx-conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
            items:
              - key: nginx.conf
                path: default.conf
