---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: gohello
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
